### ISSUE TITLE
Crash with Astral Sorcery

### ISSUE THREAD

**Issue by MuckingAboutMC** [Lemonszz/Statues#5]
**Mod Version**:  1.12.2-1.0.0
**Forge Version**: 14.23.5.2807

**This issue occurs on the lastest version of Forge? (Y/N)**:Y
**Crash Log (Post to Pastebin/Other Text hosting)**: 
https://pastebin.com/ZgDD2VKE
**What happens**:
Statue builds fine, but crashes upon right-clicking it with anything. Not sure if this is yours or AS's, will post on both.

**Comment by HellFirePvP** [comment]
_Link_
https://github.com/HellFirePvP/AstralSorcery/issues/984

**Comment by Lemonszz** [comment]
![Fixed for 1.0.1](http://lemons.party/i/x3794.png)

The actual fix is the ugliest shit ever - but it works. Will be refactored into something sensible at some point.
